CREATE TABLE IF NOT EXISTS `meta_prefetch_runs` (
	`id` BIGINT NOT NULL,
	`status` VARCHAR(32) NOT NULL,
	`trigger` VARCHAR(64) NOT NULL,
	`started_at` BIGINT NOT NULL,
	`finished_at` BIGINT NOT NULL,
	`scanned_records` INTEGER NOT NULL,
	`skipped_records` INTEGER NOT NULL,
	`repositories` INTEGER NOT NULL,
	`skipped_repositories` INTEGER NOT NULL,
	`candidates` INTEGER NOT NULL,
	`prefetched` INTEGER NOT NULL,
	`failed` INTEGER NOT NULL,
	`skipped_candidates` INTEGER NOT NULL,
	`bytes_warmed` BIGINT NOT NULL,
	`byte_budget` BIGINT NOT NULL,
	`task_budget` INTEGER NOT NULL,
	`repository_limit` INTEGER NOT NULL,
	`retry_requested` BOOLEAN NOT NULL,
	`error` TEXT NOT NULL,
	`created_at` BIGINT NOT NULL,
	`updated_at` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	KEY `idx_meta_prefetch_runs_status` (`status`),
	KEY `idx_meta_prefetch_runs_trigger` (`trigger`),
	KEY `idx_meta_prefetch_runs_started_at` (`started_at`),
	KEY `idx_meta_prefetch_runs_finished_at` (`finished_at`),
	KEY `idx_meta_prefetch_runs_created_at` (`created_at`),
	KEY `idx_meta_prefetch_runs_updated_at` (`updated_at`)
)
