CREATE TABLE IF NOT EXISTS `meta_manifests` (
	`id` BIGINT NOT NULL,
	`key` VARCHAR(512) NOT NULL,
	`alias` VARCHAR(128) NOT NULL,
	`repository` VARCHAR(255) NOT NULL,
	`reference` VARCHAR(255) NOT NULL,
	`accept_key` VARCHAR(512) NOT NULL,
	`digest` VARCHAR(128) NOT NULL,
	`media_type` VARCHAR(255) NOT NULL,
	`size` BIGINT NOT NULL,
	`object_key` VARCHAR(512) NOT NULL,
	`headers` TEXT NOT NULL,
	`expires_at` BIGINT NOT NULL,
	`created_at` BIGINT NOT NULL,
	`updated_at` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `idx_meta_manifests_key` (`key`),
	KEY `idx_meta_manifests_alias` (`alias`),
	KEY `idx_meta_manifests_repository` (`repository`),
	KEY `idx_meta_manifests_reference` (`reference`),
	KEY `idx_meta_manifests_accept_key` (`accept_key`),
	KEY `idx_meta_manifests_digest` (`digest`),
	KEY `idx_meta_manifests_expires_at` (`expires_at`),
	KEY `idx_meta_manifests_created_at` (`created_at`),
	KEY `idx_meta_manifests_updated_at` (`updated_at`),
	KEY `idx_meta_manifests_repo` (`alias`, `repository`)
)
