CREATE TABLE IF NOT EXISTS `meta_repositories` (
	`id` BIGINT NOT NULL,
	`key` VARCHAR(512) NOT NULL,
	`upstream_id` BIGINT NOT NULL,
	`alias` VARCHAR(128) NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`pull_count` BIGINT NOT NULL,
	`blob_bytes` BIGINT NOT NULL,
	`blob_link_count` BIGINT NOT NULL,
	`last_pull_at` BIGINT NOT NULL,
	`last_blob_access_at` BIGINT NOT NULL,
	`last_activity_at` BIGINT NOT NULL,
	`created_at` BIGINT NOT NULL,
	`updated_at` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `idx_meta_repositories_key` (`key`),
	KEY `idx_meta_repositories_upstream_id` (`upstream_id`),
	KEY `idx_meta_repositories_alias` (`alias`),
	KEY `idx_meta_repositories_name` (`name`),
	KEY `idx_meta_repositories_pull_count` (`pull_count`),
	KEY `idx_meta_repositories_blob_bytes` (`blob_bytes`),
	KEY `idx_meta_repositories_blob_link_count` (`blob_link_count`),
	KEY `idx_meta_repositories_last_pull_at` (`last_pull_at`),
	KEY `idx_meta_repositories_last_blob_access_at` (`last_blob_access_at`),
	KEY `idx_meta_repositories_last_activity_at` (`last_activity_at`),
	KEY `idx_meta_repositories_created_at` (`created_at`),
	KEY `idx_meta_repositories_updated_at` (`updated_at`),
	KEY `idx_meta_repositories_upstream_name` (`upstream_id`, `name`)
)
