CREATE TABLE IF NOT EXISTS `meta_endpoint_health` (
	`id` BIGINT NOT NULL,
	`key` VARCHAR(1024) NOT NULL,
	`alias` VARCHAR(128) NOT NULL,
	`registry` VARCHAR(512) NOT NULL,
	`repository` VARCHAR(255) NOT NULL,
	`latency_ewma` BIGINT NOT NULL,
	`latency_samples` BIGINT NOT NULL,
	`consecutive_failures` BIGINT NOT NULL,
	`success_count` BIGINT NOT NULL,
	`failure_count` BIGINT NOT NULL,
	`content_mismatch_count` BIGINT NOT NULL,
	`cooldown_until` BIGINT NOT NULL,
	`degraded_until` BIGINT NOT NULL,
	`last_success_at` BIGINT NOT NULL,
	`last_failure_at` BIGINT NOT NULL,
	`last_probe_at` BIGINT NOT NULL,
	`created_at` BIGINT NOT NULL,
	`updated_at` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `idx_meta_endpoint_health_key` (`key`(768)),
	KEY `idx_meta_endpoint_health_alias` (`alias`),
	KEY `idx_meta_endpoint_health_registry` (`registry`(191)),
	KEY `idx_meta_endpoint_health_repository` (`repository`),
	KEY `idx_meta_endpoint_health_consecutive_failures` (`consecutive_failures`),
	KEY `idx_meta_endpoint_health_cooldown_until` (`cooldown_until`),
	KEY `idx_meta_endpoint_health_degraded_until` (`degraded_until`),
	KEY `idx_meta_endpoint_health_last_success_at` (`last_success_at`),
	KEY `idx_meta_endpoint_health_last_failure_at` (`last_failure_at`),
	KEY `idx_meta_endpoint_health_last_probe_at` (`last_probe_at`),
	KEY `idx_meta_endpoint_health_created_at` (`created_at`),
	KEY `idx_meta_endpoint_health_updated_at` (`updated_at`),
	KEY `idx_meta_endpoint_health_endpoint` (`alias`, `registry`(191)),
	KEY `idx_meta_endpoint_health_repo` (`alias`, `registry`(191), `repository`)
)
