CREATE TABLE IF NOT EXISTS `meta_refresh_intents` (
	`id` BIGINT NOT NULL,
	`key` VARCHAR(128) NOT NULL,
	`ecosystem` VARCHAR(32) NOT NULL,
	`kind` VARCHAR(64) NOT NULL,
	`alias` VARCHAR(128) NOT NULL,
	`repository` VARCHAR(255) NOT NULL,
	`reference` VARCHAR(255) NOT NULL,
	`accept` TEXT NOT NULL,
	`due_at` BIGINT NOT NULL,
	`last_seen_at` BIGINT NOT NULL,
	`skipped` INTEGER NOT NULL,
	`created_at` BIGINT NOT NULL,
	`updated_at` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `idx_meta_refresh_intents_key` (`key`),
	KEY `idx_meta_refresh_intents_ecosystem` (`ecosystem`),
	KEY `idx_meta_refresh_intents_kind` (`kind`),
	KEY `idx_meta_refresh_intents_alias` (`alias`),
	KEY `idx_meta_refresh_intents_repository` (`repository`),
	KEY `idx_meta_refresh_intents_reference` (`reference`),
	KEY `idx_meta_refresh_intents_due_at` (`due_at`),
	KEY `idx_meta_refresh_intents_last_seen_at` (`last_seen_at`),
	KEY `idx_meta_refresh_intents_created_at` (`created_at`),
	KEY `idx_meta_refresh_intents_updated_at` (`updated_at`),
	KEY `idx_meta_refresh_intents_target` (`ecosystem`, `alias`, `repository`, `reference`)
)
