CREATE TABLE IF NOT EXISTS `meta_prefetch_outcomes` (
	`id` BIGINT NOT NULL,
	`run_id` BIGINT NOT NULL,
	`candidate_key` VARCHAR(512) NOT NULL,
	`alias` VARCHAR(128) NOT NULL,
	`repository` VARCHAR(255) NOT NULL,
	`reference` VARCHAR(255) NOT NULL,
	`source_reference` VARCHAR(255) NOT NULL,
	`status` VARCHAR(32) NOT NULL,
	`reason` TEXT NOT NULL,
	`score` INTEGER NOT NULL,
	`manifest_digest` VARCHAR(128) NOT NULL,
	`layer_count` INTEGER NOT NULL,
	`blob_count` INTEGER NOT NULL,
	`child_manifest_count` INTEGER NOT NULL,
	`bytes_warmed` BIGINT NOT NULL,
	`attempt` INTEGER NOT NULL,
	`error` TEXT NOT NULL,
	`skip_reason` TEXT NOT NULL,
	`next_retry_at` BIGINT NOT NULL,
	`started_at` BIGINT NOT NULL,
	`finished_at` BIGINT NOT NULL,
	`created_at` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	KEY `idx_meta_prefetch_outcomes_run_id` (`run_id`),
	KEY `idx_meta_prefetch_outcomes_candidate_key` (`candidate_key`),
	KEY `idx_meta_prefetch_outcomes_alias` (`alias`),
	KEY `idx_meta_prefetch_outcomes_repository` (`repository`),
	KEY `idx_meta_prefetch_outcomes_reference` (`reference`),
	KEY `idx_meta_prefetch_outcomes_source_reference` (`source_reference`),
	KEY `idx_meta_prefetch_outcomes_status` (`status`),
	KEY `idx_meta_prefetch_outcomes_manifest_digest` (`manifest_digest`),
	KEY `idx_meta_prefetch_outcomes_next_retry_at` (`next_retry_at`),
	KEY `idx_meta_prefetch_outcomes_started_at` (`started_at`),
	KEY `idx_meta_prefetch_outcomes_finished_at` (`finished_at`),
	KEY `idx_meta_prefetch_outcomes_created_at` (`created_at`),
	KEY `idx_meta_prefetch_outcomes_repo` (`alias`, `repository`)
)
