package config

import "time"

func defaultValues() map[string]any {
	return map[string]any{
		"server.listen":                        ":5000",
		"server.public_url":                    "http://localhost:5000",
		"server.read_timeout":                  30 * time.Second,
		"server.write_timeout":                 0,
		"server.idle_timeout":                  120 * time.Second,
		"log.level":                            "info",
		"log.console":                          true,
		"log.add_caller":                       false,
		"log.max_size_mb":                      100,
		"log.max_age_days":                     7,
		"log.max_backups":                      10,
		"log.time_format":                      "2006-01-02 15:04:05",
		"log.set_default":                      true,
		"log.local_time":                       true,
		"log.compress":                         true,
		"cache.backend":                        "memory",
		"cache.prefix":                         "regimux",
		"cache.default_ttl":                    10 * time.Minute,
		"cache.memory.max_items":               10000,
		"cache.redis.addrs":                    []string{"127.0.0.1:6379"},
		"cache.redis.db":                       0,
		"cache.valkey.addrs":                   []string{"127.0.0.1:6379"},
		"cache.valkey.db":                      0,
		"cache.manifest.tag_ttl":               10 * time.Minute,
		"cache.manifest.stale_if_error":        true,
		"cache.manifest.max_stale":             168 * time.Hour,
		"cache.blob.stream_and_cache":          false,
		"cache.tags.ttl":                       5 * time.Minute,
		"cache.tags.max_page_size":             1000,
		"cache.referrers.ttl":                  5 * time.Minute,
		"cache.referrers.fallback_tag":         true,
		"store.meta.driver":                    "bboltx",
		"store.meta.path":                      "data/regimux.db",
		"store.object.driver":                  "local",
		"store.object.path":                    "data/objects",
		"upstreams.hub.registry":               "https://registry-1.docker.io",
		"upstreams.hub.mirror_policy":          "ordered",
		"upstreams.hub.default_namespace":      "library",
		"upstreams.hub.tag_ttl":                10 * time.Minute,
		"upstreams.hub.auth.type":              "anonymous",
		"upstreams.hub.http.timeout":           0,
		"upstreams.hub.http.retry.enabled":     true,
		"upstreams.hub.http.retry.max_retries": 2,
		"upstreams.hub.http.retry.wait_min":    100 * time.Millisecond,
		"upstreams.hub.http.retry.wait_max":    1 * time.Second,
	}
}
